//! #647: filling a field on a PDF whose AcroForm is an *inline* dictionary in
//! the catalog (and whose widget carries an empty `/AP /N`) must set
//! `/NeedAppearances true` so viewers regenerate the appearance from `/V`+`/DA`
//! instead of honouring the empty appearance stream and rendering the field
//! blank (ISO 32000-1:2008 §12.7.3.3; Table 226 — a present `/AP` takes
//! precedence over `/DA`).
//!
//! The reporter's sample is an external PDF, so this test hand-builds a minimal
//! PDF with the same structure (inline AcroForm, merged field+widget, empty AP,
//! NO /NeedAppearances) — no external/MPL fixtures.

use pdf_oxide::editor::form_fields::FormFieldValue;
use pdf_oxide::editor::DocumentEditor;
use pdf_oxide::extractors::forms::FormExtractor;
use pdf_oxide::PdfDocument;

/// Append `id 0 obj\n<body>\nendobj\n`, recording the object's byte offset.
fn obj(buf: &mut Vec<u8>, offsets: &mut [usize], id: usize, body: &str) {
    offsets[id] = buf.len();
    buf.extend_from_slice(format!("{id} 0 obj\n").as_bytes());
    buf.extend_from_slice(body.as_bytes());
    buf.extend_from_slice(b"\nendobj\n");
}

/// A minimal one-field PDF whose AcroForm is INLINE in the catalog, with no
/// `/NeedAppearances`, and whose widget has an empty `/AP /N` form XObject.
fn inline_acroform_form() -> Vec<u8> {
    let mut buf: Vec<u8> = Vec::new();
    let mut off = vec![0usize; 7]; // ids 1..=6

    buf.extend_from_slice(b"%PDF-1.7\n%\xE2\xE3\xCF\xD3\n");

    // 1: catalog with an INLINE AcroForm (no /NeedAppearances)
    obj(
        &mut buf,
        &mut off,
        1,
        "<< /Type /Catalog /Pages 2 0 R \
         /AcroForm << /Fields [4 0 R] /DA (/Helv 0 Tf 0 g) \
         /DR << /Font << /Helv 5 0 R >> >> >> >>",
    );
    // 2: page tree
    obj(&mut buf, &mut off, 2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>");
    // 3: page, references the widget in /Annots
    obj(
        &mut buf,
        &mut off,
        3,
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] \
         /Resources << >> /Annots [4 0 R] >>",
    );
    // 4: merged text field + widget annotation, empty /AP /N -> obj 6
    obj(
        &mut buf,
        &mut off,
        4,
        "<< /FT /Tx /T (full_name) /Type /Annot /Subtype /Widget \
         /Rect [72 700 400 720] /DA (/Helv 0 Tf 0 g) /AP << /N 6 0 R >> >>",
    );
    // 5: Helvetica font for /DR
    obj(&mut buf, &mut off, 5, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
    // 6: empty appearance stream (the blank field the user sees today)
    let content = "/Tx BMC\nEMC\n";
    off[6] = buf.len();
    buf.extend_from_slice(b"6 0 obj\n");
    buf.extend_from_slice(
        format!(
            "<< /Type /XObject /Subtype /Form /BBox [0 0 328 20] /Length {} >>\nstream\n",
            content.len()
        )
        .as_bytes(),
    );
    buf.extend_from_slice(content.as_bytes());
    buf.extend_from_slice(b"endstream\nendobj\n");

    // xref
    let xref_off = buf.len();
    buf.extend_from_slice(b"xref\n0 7\n0000000000 65535 f \n");
    for id in 1..=6 {
        buf.extend_from_slice(format!("{:010} 00000 n \n", off[id]).as_bytes());
    }
    buf.extend_from_slice(b"trailer\n<< /Size 7 /Root 1 0 R >>\nstartxref\n");
    buf.extend_from_slice(format!("{xref_off}\n%%EOF\n").as_bytes());
    buf
}

fn contains_ascii(hay: &[u8], needle: &[u8]) -> bool {
    hay.windows(needle.len()).any(|w| w == needle)
}

#[test]
fn inline_acroform_fill_sets_need_appearances() {
    let form = inline_acroform_form();

    // Sanity: the synthetic form parses and exposes exactly one field.
    let doc0 = PdfDocument::from_bytes(form.clone()).unwrap();
    assert_eq!(
        FormExtractor::extract_fields(&doc0).unwrap().len(),
        1,
        "synthetic inline-AcroForm form should have 1 field"
    );

    let mut ed = DocumentEditor::from_bytes(form).unwrap();
    ed.set_form_field_value("full_name", FormFieldValue::Text("Hello".into()))
        .unwrap();
    // Default save path (full rewrite) — the path the Python `save()` hits.
    let out = ed.save_to_bytes().unwrap();

    // #647: the saved PDF must carry /NeedAppearances true so the empty /AP /N
    // is regenerated by the viewer rather than rendered blank.
    assert!(
        contains_ascii(&out, b"/NeedAppearances") && contains_ascii(&out, b"NeedAppearances true"),
        "filled inline-AcroForm PDF must set /NeedAppearances true (#647)"
    );

    // The value must still round-trip.
    let doc = PdfDocument::from_bytes(out).unwrap();
    let fields = FormExtractor::extract_fields(&doc).unwrap();
    assert_eq!(fields.len(), 1, "field must survive fill+save");
    let v = format!("{:?}", fields[0].value);
    assert!(v.contains("Hello"), "re-read value must equal Hello; got {v}");
}
