defmodule PdfOxide.Native do
  @moduledoc false
  # NIF loader. The compiled NIF (priv/pdf_oxide_nif) bridges to the pdf_oxide
  # C ABI; every text-producing function runs on a dirty CPU scheduler. All
  # functions here are replaced at load time — the bodies raise if the NIF
  # failed to load.
  @on_load :load_nif

  def load_nif do
    path = :filename.join(:code.priv_dir(:pdf_oxide), ~c"pdf_oxide_nif")
    :erlang.load_nif(path, 0)
  end

  defp nif_error, do: :erlang.nif_error(:nif_not_loaded)

  def from_markdown(_md), do: nif_error()
  def from_html(_html), do: nif_error()
  def from_text(_text), do: nif_error()
  def pdf_save(_pdf, _path), do: nif_error()
  def pdf_save_to_bytes(_pdf), do: nif_error()
  def doc_open(_path), do: nif_error()
  def doc_open_bytes(_bytes), do: nif_error()
  def doc_open_pw(_path, _pw), do: nif_error()
  def doc_page_count(_doc), do: nif_error()
  def doc_version(_doc), do: nif_error()
  def doc_is_encrypted(_doc), do: nif_error()
  def doc_has_structure_tree(_doc), do: nif_error()
  def doc_extract_text(_doc, _page), do: nif_error()
  def doc_to_plain_text(_doc, _page), do: nif_error()
  def doc_to_markdown(_doc, _page), do: nif_error()
  def doc_to_html(_doc, _page), do: nif_error()
  def doc_to_markdown_all(_doc), do: nif_error()
  def doc_to_html_all(_doc), do: nif_error()
  def doc_to_plain_text_all(_doc), do: nif_error()
  def doc_authenticate(_doc, _pw), do: nif_error()
  def doc_extract_structured_json(_doc, _page), do: nif_error()
  def doc_extract_chars(_doc, _page), do: nif_error()
  def doc_extract_words(_doc, _page), do: nif_error()
  def doc_extract_text_lines(_doc, _page), do: nif_error()
  def doc_extract_tables(_doc, _page), do: nif_error()
  def doc_embedded_fonts(_doc, _page), do: nif_error()
  def doc_embedded_images(_doc, _page), do: nif_error()
  def doc_page_annotations(_doc, _page), do: nif_error()
  def doc_extract_paths(_doc, _page), do: nif_error()
  def doc_search_page(_doc, _page, _term, _case_sensitive), do: nif_error()
  def doc_search_all(_doc, _term, _case_sensitive), do: nif_error()
  def doc_render_page(_doc, _page_index, _format), do: nif_error()
  def doc_render_page_zoom(_doc, _page_index, _zoom, _format), do: nif_error()
  def doc_render_page_thumbnail(_doc, _page_index, _size, _format), do: nif_error()
  def img_save(_img, _path), do: nif_error()
  def doc_close(_doc), do: nif_error()
  def pdf_close(_pdf), do: nif_error()

  # document editor
  def editor_open(_path), do: nif_error()
  def editor_open_bytes(_bytes), do: nif_error()
  def editor_is_modified(_ed), do: nif_error()
  def editor_source_path(_ed), do: nif_error()
  def editor_version(_ed), do: nif_error()
  def editor_page_count(_ed), do: nif_error()
  def editor_get_producer(_ed), do: nif_error()
  def editor_set_producer(_ed, _value), do: nif_error()
  def editor_get_creation_date(_ed), do: nif_error()
  def editor_set_creation_date(_ed, _date), do: nif_error()
  def editor_save(_ed, _path), do: nif_error()
  def editor_save_to_bytes(_ed), do: nif_error()
  def editor_save_to_bytes_with_options(_ed, _compress, _gc, _linearize), do: nif_error()
  def editor_extract_pages_to_bytes(_ed, _pages), do: nif_error()
  def editor_convert_to_pdf_a(_ed, _level), do: nif_error()
  def editor_save_encrypted_to_bytes(_ed, _user_pw, _owner_pw), do: nif_error()
  def editor_merge_from_bytes(_ed, _bytes), do: nif_error()
  def editor_embed_file(_ed, _name, _bytes), do: nif_error()
  def editor_apply_page_redactions(_ed, _page), do: nif_error()
  def editor_apply_all_redactions(_ed), do: nif_error()
  def editor_rotate_all_pages(_ed, _degrees), do: nif_error()
  def editor_rotate_page_by(_ed, _page, _degrees), do: nif_error()
  def editor_get_media_box(_ed, _page), do: nif_error()
  def editor_set_media_box(_ed, _page, _x, _y, _w, _h), do: nif_error()
  def editor_get_crop_box(_ed, _page), do: nif_error()
  def editor_set_crop_box(_ed, _page, _x, _y, _w, _h), do: nif_error()
  def editor_erase_regions(_ed, _page, _rects), do: nif_error()
  def editor_clear_erase_regions(_ed, _page), do: nif_error()
  def editor_is_marked_for_flatten(_ed, _page), do: nif_error()
  def editor_unmark_for_flatten(_ed, _page), do: nif_error()
  def editor_is_marked_for_redaction(_ed, _page), do: nif_error()
  def editor_unmark_for_redaction(_ed, _page), do: nif_error()
  def editor_delete_page(_ed, _page_index), do: nif_error()
  def editor_move_page(_ed, _from, _to), do: nif_error()
  def editor_get_page_rotation(_ed, _page), do: nif_error()
  def editor_set_page_rotation(_ed, _page, _degrees), do: nif_error()
  def editor_erase_region(_ed, _page, _x, _y, _w, _h), do: nif_error()
  def editor_flatten_annotations(_ed, _page), do: nif_error()
  def editor_flatten_all_annotations(_ed), do: nif_error()
  def editor_crop_margins(_ed, _left, _right, _top, _bottom), do: nif_error()
  def editor_merge_from(_ed, _source_path), do: nif_error()
  def editor_save_encrypted(_ed, _path, _user_pw, _owner_pw), do: nif_error()
  def editor_set_form_field_value(_ed, _name, _value), do: nif_error()
  def editor_flatten_forms(_ed), do: nif_error()
  def editor_flatten_forms_on_page(_ed, _page_index), do: nif_error()
  def editor_flatten_warnings_count(_ed), do: nif_error()
  def editor_flatten_warning(_ed, _index), do: nif_error()
  def editor_close(_ed), do: nif_error()
end
