//! JNI surface for `fyi.oxide.pdf.Pdf` — PDF creation API.
//!
//! Wraps [`pdf_oxide::api::PdfBuilder`] for markdown→PDF and
//! HTML→PDF generation. The Java {@link fyi.oxide.pdf.Pdf} holds a
//! `*mut Vec<u8>` (leaked Box of the generated bytes) which the
//! `save()` method copies out as a `byte[]` and which `close()`
//! frees.

use jni::errors::{Error as JniError, ThrowRuntimeExAndDefault};
use jni::objects::{JByteArray, JClass, JString};
use jni::sys::{jbyteArray, jlong};
use jni::EnvUnowned;
use pdf_oxide::api::PdfBuilder;

use crate::error::throw_pdf;

/// SAFETY: caller must guarantee `handle` is a leaked Box<Vec<u8>>
/// pointer not yet freed.
#[inline]
unsafe fn bytes_ref<'h>(handle: jlong) -> &'h Vec<u8> {
    debug_assert!(handle != 0, "JNI: Pdf handle was 0");
    // SAFETY: caller upholds the unsafe fn contract — handle was checked by the JNI panic-barrier and Java's checked-handle pattern guarantees non-null + valid lifetime.
    unsafe { &*(handle as *const Vec<u8>) }
}

#[no_mangle]
pub extern "system" fn Java_fyi_oxide_pdf_Pdf_nativeFromMarkdown<'local>(
    mut env: EnvUnowned<'local>,
    _class: JClass<'local>,
    content: JString<'local>,
) -> jlong {
    env.with_env(|env| -> Result<jlong, JniError> {
        let s: String = content.try_to_string(env)?;
        match PdfBuilder::new().from_markdown(&s) {
            Ok(pdf) => {
                let bytes = pdf.into_bytes();
                Ok(Box::into_raw(Box::new(bytes)) as jlong)
            },
            Err(e) => {
                throw_pdf(env, &e)?;
                Ok(0)
            },
        }
    })
    .resolve::<ThrowRuntimeExAndDefault>()
}

/// `nativeFromImages` — build a multi-page PDF from a list of
/// image byte arrays (auto-detected JPEG/PNG per
/// `pdf_oxide::writer::ImageData::from_bytes`). Each image becomes
/// one page.
#[no_mangle]
pub extern "system" fn Java_fyi_oxide_pdf_Pdf_nativeFromImages<'local>(
    mut env: EnvUnowned<'local>,
    _class: JClass<'local>,
    images: jni::objects::JObjectArray<'local>,
) -> jlong {
    env.with_env(|env| -> Result<jlong, JniError> {
        let len = images.len(env)?;
        if len == 0 {
            let cls = jni::strings::JNIString::from("java/lang/IllegalArgumentException");
            let msg = jni::strings::JNIString::from("at least one image is required");
            let _ = env.throw_new(&cls, &msg);
            return Err(JniError::JavaException);
        }
        let mut img_data: Vec<pdf_oxide::writer::ImageData> = Vec::with_capacity(len);
        for i in 0..len {
            let inner = images.get_element(env, i)?;
            // Defensive null check: a Java List<byte[]> can legally
            // contain null elements (different from "empty array"),
            // and JNI's convert_byte_array on a null reference is UB.
            if inner.is_null() {
                let cls = jni::strings::JNIString::from("java/lang/IllegalArgumentException");
                let msg = jni::strings::JNIString::from(format!("image at index {} is null", i));
                let _ = env.throw_new(&cls, &msg);
                return Err(JniError::JavaException);
            }
            // The element is byte[]; auto-ref to JByteArray via unsafe cast
            // of the JObject raw pointer (we know the runtime type from
            // the Java declaration of byte[][]).
            let inner_raw = inner.into_raw() as jni::sys::jbyteArray;
            let inner_arr = unsafe { jni::objects::JByteArray::from_raw(env, inner_raw) };
            let bytes: Vec<u8> = env.convert_byte_array(&inner_arr)?;
            match pdf_oxide::writer::ImageData::from_bytes(&bytes) {
                Ok(d) => img_data.push(d),
                Err(e) => {
                    let cls =
                        jni::strings::JNIString::from("fyi/oxide/pdf/exception/PdfParseException");
                    let msg =
                        jni::strings::JNIString::from(format!("image {} bytes invalid: {}", i, e));
                    let _ = env.throw_new(&cls, &msg);
                    return Err(JniError::JavaException);
                },
            }
        }
        match PdfBuilder::new().from_image_data_multiple(img_data) {
            Ok(pdf) => {
                let bytes = pdf.into_bytes();
                Ok(Box::into_raw(Box::new(bytes)) as jlong)
            },
            Err(e) => {
                throw_pdf(env, &e)?;
                Ok(0)
            },
        }
    })
    .resolve::<ThrowRuntimeExAndDefault>()
}

#[no_mangle]
pub extern "system" fn Java_fyi_oxide_pdf_Pdf_nativeFromHtml<'local>(
    mut env: EnvUnowned<'local>,
    _class: JClass<'local>,
    content: JString<'local>,
) -> jlong {
    env.with_env(|env| -> Result<jlong, JniError> {
        let s: String = content.try_to_string(env)?;
        match PdfBuilder::new().from_html(&s) {
            Ok(pdf) => {
                let bytes = pdf.into_bytes();
                Ok(Box::into_raw(Box::new(bytes)) as jlong)
            },
            Err(e) => {
                throw_pdf(env, &e)?;
                Ok(0)
            },
        }
    })
    .resolve::<ThrowRuntimeExAndDefault>()
}

/// `nativeSaveBytes` — copy the held byte vector into a fresh Java
/// `byte[]`. Does NOT consume the handle (so `save()` can be called
/// multiple times on the same `Pdf` instance).
#[no_mangle]
pub extern "system" fn Java_fyi_oxide_pdf_Pdf_nativeSaveBytes<'local>(
    mut env: EnvUnowned<'local>,
    _class: JClass<'local>,
    handle: jlong,
) -> jbyteArray {
    env.with_env(|env| -> Result<jbyteArray, JniError> {
        let bytes = unsafe { bytes_ref(handle) };
        let arr: JByteArray = env.byte_array_from_slice(bytes.as_slice())?;
        Ok(arr.into_raw())
    })
    .resolve::<ThrowRuntimeExAndDefault>()
}

/// `nativeClose` — free the held byte vector.
///
/// # Safety
///
/// JVM-invoked. `handle` must be a valid pointer from a previous
/// `nativeFromMarkdown` / `nativeFromHtml` call, not yet freed.
#[no_mangle]
pub extern "system" fn Java_fyi_oxide_pdf_Pdf_nativeClose<'local>(
    mut env: EnvUnowned<'local>,
    _class: JClass<'local>,
    handle: jlong,
) {
    let _ = env
        .with_env(|_env| -> Result<(), JniError> {
            if handle != 0 {
                // SAFETY: handle was returned by nativeFrom* and not yet freed.
                unsafe {
                    drop(Box::from_raw(handle as *mut Vec<u8>));
                }
            }
            Ok(())
        })
        .resolve::<ThrowRuntimeExAndDefault>();
}
